const exhititionList={
    floor1:[
        /** 1号馆**/
        {
            src:require('@/assets/p11.png'),
            opacity:'0',
            left:'55.68%',
            top:'19.80%',
            pavilion:'1',
            width:'21px',
            height:'24px',
            index:0,
            exhition:'1C6-022'
        },
        {
            src:require('@/assets/p11.png'),
            opacity:'0',
            left:'59.62%',
            top:'21.01%',
            pavilion:'1',
            width:'21px',
            height:'24px',
            index:1,
            exhition:'1A3-011'
        },
        {
            src:require('@/assets/p11.png'),
            opacity:'0',
            left:'56.78%',
            top:'16.90%',
            pavilion:'1',
            width:'21px',
            height:'24px',
            index:2,
            exhition:'1A2-004(03)'
        },
        {
            src:require('@/assets/p11.png'),
            opacity:'0',
            left:'60.73%',
            top:'18.11%',
            pavilion:'1',
            width:'21px',
            height:'24px',
            index:3,
            exhition:'1C2-001(07)'
        },
        {
            src:require('@/assets/p11.png'),
            opacity:'0',
            left:'57.89%',
            top:'14.25%',
            pavilion:'1',
            width:'21px',
            height:'24px',
            index:4,
            exhition:'1A7-006'
        },
        {
            src:require('@/assets/p11.png'),
            opacity:'0',
            left:'61.83%',
            top:'15.46%',
            pavilion:'1',
            width:'21px',
            height:'24px',
            index:5,
            exhition:'1C2-002(01)'
        },
        {
            src:require('@/assets/p11.png'),
            opacity:'0',
            left:'59.0%',
            top:'11.35%',
            pavilion:'1',
            width:'21px',
            height:'24px',
            index:6,
            exhition:'1A4-008'
        },
        {
            src:require('@/assets/p11.png'),
            opacity:'0',
            left:'62.78%',
            top:'12.80%',
            pavilion:'1',
            width:'21px',
            height:'24px',
            index:7,
            exhition:'1C2-003'
        },
        {
            src:require('@/assets/p11.png'),
            opacity:'0',
            left:'59.94%',
            top:'8.70%',
            pavilion:'1',
            width:'21px',
            height:'24px',
            index:8,
            exhition:'1C2-001(21)'
        },
        {
            src:require('@/assets/p11.png'),
            opacity:'0',
            left:'63.88%',
            top:'10.14%',
            pavilion:'1',
            width:'21px',
            height:'24px',
            index:9,
            exhition:'1C4-001'
        },
        {
            src:require('@/assets/other1n.png'),
            opacity:'0',
            left:'54.57%',
            top:'22.46%',
            pavilion:'1',
            width:'21px',
            height:'24px',
            index:'other'
        },
        {
            src:require('@/assets/other1l.png'),
            opacity:'0',
            left:'61.04%',
            top:'7.00%',
            pavilion:'1',
            width:'21px',
            height:'24px',
            index:'other2'
        },
        {
            src:require('@/assets/other1l.png'),
            opacity:'0',
            left:'64.83%',
            top:'8.21%',
            pavilion:'1',
            width:'21px',
            height:'24px',
            index:'other3'
        },
        /** 2号馆**/
        {
            src:require('@/assets/p21.png'),
            opacity:'0',
            left:'42.90%',
            top:'15.46%',
            pavilion:'2',
            width:'20px',
            height:'24px',
            index:0
        },
        {
            src:require('@/assets/p21.png'),
            opacity:'0',
            left:'47%',
            top:'16.90%',
            pavilion:'2',
            width:'20px',
            height:'24px',
            index:1
        },
        {
            src:require('@/assets/p21.png'),
            opacity:'0',
            left:'44.32%',
            top:'12.56%',
            pavilion:'2',
            width:'20px',
            height:'24px',
            index:2
        },
        {
            src:require('@/assets/p21.png'),
            opacity:'0',
            left:'48.26%',
            top:'14%',
            pavilion:'2',
            width:'20px',
            height:'24px',
            index:3
        },
        {
            src:require('@/assets/p21.png'),
            opacity:'0',
            left:'45.58%',
            top:'9.9%',
            pavilion:'2',
            width:'20px',
            height:'24px',
            index:4
        },
        {
            src:require('@/assets/p21.png'),
            opacity:'0',
            left:'49.68%',
            top:'11.11%',
            pavilion:'2',
            width:'20px',
            height:'24px',
            index:5
        },
        {
            src:require('@/assets/p21.png'),
            opacity:'0',
            left:'47.0%',
            top:'7%',
            pavilion:'2',
            width:'20px',
            height:'24px',
            index:6
        },
        {
            src:require('@/assets/p21.png'),
            opacity:'0',
            left:'50.78%',
            top:'8.45%',
            pavilion:'2',
            width:'20px',
            height:'24px',
            index:7
        },
        {
            src:require('@/assets/p21.png'),
            opacity:'0',
            left:'48.26%',
            top:'4.83%',
            pavilion:'2',
            width:'20px',
            height:'24px',
            index:8
        },
        {
            src:require('@/assets/p21.png'),
            opacity:'0',
            left:'52.05%',
            top:'6.04%',
            pavilion:'2',
            width:'20px',
            height:'24px',
            index:9
        },
        {
            src:require('@/assets/other2n.png'),
            opacity:'0',
            left:'45.90%',
            top:'19.81%',
            pavilion:'2',
            width:'20px',
            height:'24px',
            index:'other'
        },
        {
            src:require('@/assets/other2l.png'),
            opacity:'0',
            left:'49.37%',
            top:'3.38%',
            pavilion:'2',
            width:'20px',
            height:'24px',
            index:'other2'
        },
        {
            src:require('@/assets/other2l.png'),
            opacity:'0',
            left:'53.15%',
            top:'4.59%',
            pavilion:'2',
            width:'20px',
            height:'24px',
            index:'other3'
        },
        /** 3号馆**/
        {
            src:require('@/assets/p31.png'),
            opacity:'0',
            left:'28.39%',
            top:'21.98%',
            pavilion:'3',
            width:'24px',
            height:'27px',
            index:0
        },
        {
            src:require('@/assets/p31.png'),
            opacity:'0',
            left:'30.28%',
            top:'18.59%',
            pavilion:'3',
            width:'24px',
            height:'27px',
            index:1
        },
        {
            src:require('@/assets/p31.png'),
            opacity:'0',
            left:'25.08%',
            top:'20.53%',
            pavilion:'3',
            width:'24px',
            height:'27px',
            index:2
        },
        {
            src:require('@/assets/p31.png'),
            opacity:'0',
            left:'26.97%',
            top:'17.39%',
            pavilion:'3',
            width:'24px',
            height:'27px',
            index:3
        },
        {
            src:require('@/assets/p31.png'),
            opacity:'0',
            left:'21.77%',
            top:'19.32%',
            pavilion:'3',
            width:'24px',
            height:'27px',
            index:4
        },
        {
            src:require('@/assets/p31.png'),
            opacity:'0',
            left:'23.82%',
            top:'16.18%',
            pavilion:'3',
            width:'24px',
            height:'27px',
            index:5
        },
        {
            src:require('@/assets/p31.png'),
            opacity:'0',
            left:'18.45%',
            top:'17.87%',
            pavilion:'3',
            width:'24px',
            height:'27px',
            index:6
        },
        {
            src:require('@/assets/p31.png'),
            opacity:'0',
            left:'20.35%',
            top:'14.73%',
            pavilion:'3',
            width:'24px',
            height:'27px',
            index:7
        },
        {
            src:require('@/assets/p31.png'),
            opacity:'0',
            left:'14.98%',
            top:'16.67%',
            pavilion:'3',
            width:'24px',
            height:'27px',
            index:8
        },
        {
            src:require('@/assets/p31.png'),
            opacity:'0',
            left:'17.03%',
            top:'13.53%',
            pavilion:'3',
            width:'24px',
            height:'27px',
            index:9
        },
        {
            src:require('@/assets/other3n.png'),
            opacity:'0',
            left:'31.55%',
            top:'23.19%',
            pavilion:'3',
            width:'24px',
            height:'27px',
            index:'other'
        },
        {
            src:require('@/assets/other3l.png'),
            opacity:'0',
            left:'13.41%',
            top:'16.18%',
            pavilion:'3',
            width:'24px',
            height:'27px',
            index:'other2'
        },
        {
            src:require('@/assets/other3l.png'),
            opacity:'0',
            left:'15.62%',
            top:'13.04%',
            pavilion:'3',
            width:'24px',
            height:'27px',
            index:'other3'
        },
        /** 4.1号馆**/
        {
            src:require('@/assets/p411.png'),
            opacity:'0',
            left:'22%',
            top:'34%',
            pavilion:'4.1',
            width:'25px',
            height:'28px',
            index:0
        },
        {
            src:require('@/assets/p411.png'),
            opacity:'0',
            left:'24.6%',
            top:'29.4%',
            pavilion:'4.1',
            width:'25px',
            height:'28px',
            index:1
        },
        {
            src:require('@/assets/p411.png'),
            opacity:'0',
            left:'18.5%',
            top:'32.6%',
            pavilion:'4.1',
            width:'25px',
            height:'28px',
            index:2
        },
        {
            src:require('@/assets/p411.png'),
            opacity:'0',
            left:'21.3%',
            top:'28%',
            pavilion:'4.1',
            width:'25px',
            height:'28px',
            index:3
        },
        {
            src:require('@/assets/p411.png'),
            opacity:'0',
            left:'15%',
            top:'31%',
            pavilion:'4.1',
            width:'25px',
            height:'28px',
            index:4
        },
        {
            src:require('@/assets/p411.png'),
            opacity:'0',
            left:'17.8%',
            top:'26.5%',
            pavilion:'4.1',
            width:'25px',
            height:'28px',
            index:5
        },
        {
            src:require('@/assets/p411.png'),
            opacity:'0',
            left:'11.5%',
            top:'29.7%',
            pavilion:'4.1',
            width:'25px',
            height:'28px',
            index:6
        },
        {
            src:require('@/assets/p411.png'),
            opacity:'0',
            left:'14.3%',
            top:'25.1%',
            pavilion:'4.1',
            width:'25px',
            height:'28px',
            index:7
        },
        {
            src:require('@/assets/p411.png'),
            opacity:'0',
            left:'8.2%',
            top:'28.3%',
            pavilion:'4.1',
            width:'25px',
            height:'28px',
            index:8
        },
        {
            src:require('@/assets/p411.png'),
            opacity:'0',
            left:'11%',
            top:'23.9%',
            pavilion:'4.1',
            width:'25px',
            height:'28px',
            index:9
        },
        {
            src:require('@/assets/other4n.png'),
            opacity:'0',
            left:'27.92%',
            top:'30.92%',
            pavilion:'4.1',
            width:'25px',
            height:'28px',
            index:'other'
        },
        {
            src:require('@/assets/other4l.png'),
            opacity:'0',
            left:'6.15%',
            top:'27.54%',
            pavilion:'4.1',
            width:'25px',
            height:'28px',
            index:'other2'
        },
        {
            src:require('@/assets/other4l.png'),
            opacity:'0',
            left:'8.99%',
            top:'23.19%',
            pavilion:'4.1',
            width:'25px',
            height:'28px',
            index:'other3'
        },
        /** 5.1号馆**/
        {
            src:require('@/assets/p51.png'),
            opacity:'0',
            left:'31.55%',
            top:'49.76%',
            pavilion:'5.1',
            width:'27px',
            height:'30px',
            index:0
        },
        {
            src:require('@/assets/p51.png'),
            opacity:'0',
            left:'26.66%',
            top:'48.07%',
            pavilion:'5.1',
            width:'27px',
            height:'30px',
            index:1
        },
        {
            src:require('@/assets/p51.png'),
            opacity:'0',
            left:'29.65%',
            top:'53.38%',
            pavilion:'5.1',
            width:'27px',
            height:'30px',
            index:2
        },
        {
            src:require('@/assets/p51.png'),
            opacity:'0',
            left:'24.76%',
            top:'51.69%',
            pavilion:'5.1',
            width:'27px',
            height:'30px',
            index:3
        },
        {
            src:require('@/assets/p51.png'),
            opacity:'0',
            left:'27.60%',
            top:'57.49%',
            pavilion:'5.1',
            width:'27px',
            height:'30px',
            index:4
        },
        {
            src:require('@/assets/p51.png'),
            opacity:'0',
            left:'22.71%',
            top:'55.80%',
            pavilion:'5.1',
            width:'27px',
            height:'30px',
            index:5
        },
        {
            src:require('@/assets/p51.png'),
            opacity:'0',
            left:'25.55%',
            top:'62%',
            pavilion:'5.1',
            width:'27px',
            height:'30px',
            index:6
        },
        {
            src:require('@/assets/p51.png'),
            opacity:'0',
            left:'20.5%',
            top:'60.14%',
            pavilion:'5.1',
            width:'27px',
            height:'30px',
            index:7
        },
        {
            src:require('@/assets/p51.png'),
            opacity:'0',
            left:'23.34%',
            top:'66.67%',
            pavilion:'5.1',
            width:'27px',
            height:'30px',
            index:8
        },
        {
            src:require('@/assets/p51.png'),
            opacity:'0',
            left:'18.30%',
            top:'64.73%',
            pavilion:'5.1',
            width:'27px',
            height:'30px',
            index:9
        },
        {
            src:require('@/assets/other5n.png'),
            opacity:'0',
            left:'33.44%',
            top:'45.89%',
            pavilion:'5.1',
            width:'27px',
            height:'30px',
            index:'other'
        },
        {
            src:require('@/assets/other5l.png'),
            opacity:'0',
            left:'17.03%',
            top:'69.08%',
            pavilion:'5.1',
            width:'27px',
            height:'30px',
            index:'other2'
        },
        {
            src:require('@/assets/other5l.png'),
            opacity:'0',
            left:'22.08%',
            top:'71.04%',
            pavilion:'5.1',
            width:'27px',
            height:'30px',
            index:'other3'
        },
        /** 6.1号馆**/
        {
            src:require('@/assets/p61.png'),
            opacity:'0',
            left:'46.53%',
            top:'56.28%',
            pavilion:'6.1',
            width:'27px',
            height:'32px',
            index:0
        },
        {
            src:require('@/assets/p61.png'),
            opacity:'0',
            left:'41.48%',
            top:'53.86%',
            pavilion:'6.1',
            width:'27px',
            height:'32px',
            index:1
        },
        {
            src:require('@/assets/p61.png'),
            opacity:'0',
            left:'44.79%',
            top:'60.39%',
            pavilion:'6.1',
            width:'27px',
            height:'32px',
            index:2
        },
        {
            src:require('@/assets/p61.png'),
            opacity:'0',
            left:'39.75%',
            top:'57.73%',
            pavilion:'6.1',
            width:'27px',
            height:'32px',
            index:3
        },
        {
            src:require('@/assets/p61.png'),
            opacity:'0',
            left:'43.22%',
            top:'64.98%',
            pavilion:'6.1',
            width:'27px',
            height:'32px',
            index:4
        },
        {
            src:require('@/assets/p61.png'),
            opacity:'0',
            left:'38.01%',
            top:'62.08%',
            pavilion:'6.1',
            width:'27px',
            height:'32px',
            index:5
        },
        {
            src:require('@/assets/p61.png'),
            opacity:'0',
            left:'41.17%',
            top:'69.32%',
            pavilion:'6.1',
            width:'27px',
            height:'32px',
            index:6
        },
        {
            src:require('@/assets/p61.png'),
            opacity:'0',
            left:'35.96%',
            top:'66.67%',
            pavilion:'6.1',
            width:'27px',
            height:'32px',
            index:7
        },
        {
            src:require('@/assets/p61.png'),
            opacity:'0',
            left:'39.27%',
            top:'74.15%',
            pavilion:'6.1',
            width:'27px',
            height:'32px',
            index:8
        },
        {
            src:require('@/assets/p61.png'),
            opacity:'0',
            left:'34.07%',
            top:'71.25%',
            pavilion:'6.1',
            width:'27px',
            height:'32px',
            index:9
        },
        {
            src:require('@/assets/other6n.png'),
            opacity:'0',
            left:'43.22%',
            top:'49.76%',
            pavilion:'6.1',
            width:'27px',
            height:'32px',
            index:'other'
        },
        {
            src:require('@/assets/other6l.png'),
            opacity:'0',
            left:'32.65%',
            top:'75.85%',
            pavilion:'6.1',
            width:'27px',
            height:'32px',
            index:'other2'
        },
        {
            src:require('@/assets/other6l.png'),
            opacity:'0',
            left:'37.85%',
            top:'78.50%',
            pavilion:'6.1',
            width:'27px',
            height:'32px',
            index:'other3'
        },
        /** 7.1号馆**/
        {
            src:require('@/assets/p71.png'),
            opacity:'0',
            left:'65.46%',
            top:'45.89%',
            pavilion:'7.1',
            width:'23px',
            height:'29px',
            index:0
        },
        {
            src:require('@/assets/p71.png'),
            opacity:'0',
            left:'64.04%',
            top:'52.42%',
            pavilion:'7.1',
            width:'23px',
            height:'29px',
            index:1
        },
        {
            src:require('@/assets/p71.png'),
            opacity:'0',
            left:'69.40%',
            top:'47.34%',
            pavilion:'7.1',
            width:'23px',
            height:'29px',
            index:2
        },
        {
            src:require('@/assets/p71.png'),
            opacity:'0',
            left:'67.98%',
            top:'54.11%',
            pavilion:'7.1',
            width:'23px',
            height:'29px',
            index:3
        },
        {
            src:require('@/assets/p71.png'),
            opacity:'0',
            left:'73.34%',
            top:'49.03%',
            pavilion:'7.1',
            width:'23px',
            height:'29px',
            index:4
        },
        {
            src:require('@/assets/p71.png'),
            opacity:'0',
            left:'72.08%',
            top:'55.56%',
            pavilion:'7.1',
            width:'23px',
            height:'29px',
            index:5
        },
        {
            src:require('@/assets/p71.png'),
            opacity:'0',
            left:'77.13%',
            top:'50.48%',
            pavilion:'7.1',
            width:'23px',
            height:'29px',
            index:6
        },
        {
            src:require('@/assets/p71.png'),
            opacity:'0',
            left:'76.02%',
            top:'57.24%',
            pavilion:'7.1',
            width:'23px',
            height:'29px',
            index:7
        },
        {
            src:require('@/assets/p71.png'),
            opacity:'0',
            left:'81.07%',
            top:'51.93%',
            pavilion:'7.1',
            width:'23px',
            height:'29px',
            index:8
        },
        {
            src:require('@/assets/p71.png'),
            opacity:'0',
            left:'79.97%',
            top:'58.70%',
            pavilion:'7.1',
            width:'23px',
            height:'29px',
            index:9
        },
        {
            src:require('@/assets/other7n.png'),
            opacity:'0',
            left:'61.83%',
            top:'44.44%',
            pavilion:'7.1',
            width:'23px',
            height:'29px',
            index:'other'
        },
        {
            src:require('@/assets/other7l.png'),
            opacity:'0',
            left:'83.60%',
            top:'60.14%',
            pavilion:'7.1',
            width:'23px',
            height:'29px',
            index:'other2'
        },
        {
            src:require('@/assets/other7l.png'),
            opacity:'0',
            left:'84.70%',
            top:'53.38%',
            pavilion:'7.1',
            width:'23px',
            height:'29px',
            index:'other3'
        },
        /** 8.1号馆**/
        // {
        //     src:require('@/assets/p81.png'),
        //     opacity:'0',
        //     left:'68.45%',
        //     top:'31.16%',
        //     pavilion:'8.1',
        //     width:'23px',
        //     height:'29px'
        // },
        // {
        //     src:require('@/assets/p81.png'),
        //     opacity:'0',
        //     left:'67.20%',
        //     top:'36.23%',
        //     pavilion:'8.1',
        //     width:'23px',
        //     height:'29px'
        // },
        // {
        //     src:require('@/assets/p81.png'),
        //     opacity:'0',
        //     left:'72.40%',
        //     top:'32.85%',
        //     pavilion:'8.1',
        //     width:'23px',
        //     height:'29px'
        // },
        // {
        //     src:require('@/assets/p81.png'),
        //     opacity:'0',
        //     left:'71.14%',
        //     top:'37.92%',
        //     pavilion:'8.1',
        //     width:'23px',
        //     height:'29px'
        // },
        // {
        //     src:require('@/assets/p81.png'),
        //     opacity:'0',
        //     left:'76.34%',
        //     top:'34.3%',
        //     pavilion:'8.1',
        //     width:'23px',
        //     height:'29px'
        // },
        // {
        //     src:require('@/assets/p81.png'),
        //     opacity:'0',
        //     left:'75.24%',
        //     top:'39.61%',
        //     pavilion:'8.1',
        //     width:'23px',
        //     height:'29px'
        // },
        // {
        //     src:require('@/assets/p81.png'),
        //     opacity:'0',
        //     left:'80.13%',
        //     top:'36%',
        //     pavilion:'8.1',
        //     width:'23px',
        //     height:'29px'
        // },
        // {
        //     src:require('@/assets/p81.png'),
        //     opacity:'0',
        //     left:'79.18%',
        //     top:'41.06%',
        //     pavilion:'8.1',
        //     width:'23px',
        //     height:'29px'
        // },
        // {
        //     src:require('@/assets/p81.png'),
        //     opacity:'0',
        //     left:'84.07%',
        //     top:'37.44%',
        //     pavilion:'8.1',
        //     width:'23px',
        //     height:'29px'
        // },
        // {
        //     src:require('@/assets/p81.png'),
        //     opacity:'0',
        //     left:'83.12%',
        //     top:'42.75%',
        //     pavilion:'8.1',
        //     width:'23px',
        //     height:'29px'
        // }
    ],
    floor2:[
        /** 5.2号馆**/
        {
            src:require('@/assets/p51.png'),
            opacity:'0',
            left:'31.55%',
            top:'49.76%',
            pavilion:'5.2',
            width:'27px',
            height:'30px',
            index:0
        },
        {
            src:require('@/assets/p51.png'),
            opacity:'0',
            left:'26.66%',
            top:'48.07%',
            pavilion:'5.2',
            width:'27px',
            height:'30px',
            index:1
        },
        {
            src:require('@/assets/p51.png'),
            opacity:'0',
            left:'29.65%',
            top:'53.38%',
            pavilion:'5.2',
            width:'27px',
            height:'30px',
            index:2
        },
        {
            src:require('@/assets/p51.png'),
            opacity:'0',
            left:'24.76%',
            top:'51.69%',
            pavilion:'5.2',
            width:'27px',
            height:'30px',
            index:3
        },
        {
            src:require('@/assets/p51.png'),
            opacity:'0',
            left:'27.60%',
            top:'57.49%',
            pavilion:'5.2',
            width:'27px',
            height:'30px',
            index:4
        },
        {
            src:require('@/assets/p51.png'),
            opacity:'0',
            left:'22.71%',
            top:'55.80%',
            pavilion:'5.2',
            width:'27px',
            height:'30px',
            index:5
        },
        {
            src:require('@/assets/p51.png'),
            opacity:'0',
            left:'25.55%',
            top:'62%',
            pavilion:'5.2',
            width:'27px',
            height:'30px',
            index:6
        },
        {
            src:require('@/assets/p51.png'),
            opacity:'0',
            left:'20.5%',
            top:'60.14%',
            pavilion:'5.2',
            width:'27px',
            height:'30px',
            index:7
        },
        {
            src:require('@/assets/p51.png'),
            opacity:'0',
            left:'23.34%',
            top:'66.67%',
            pavilion:'5.2',
            width:'27px',
            height:'30px',
            index:8
        },
        {
            src:require('@/assets/p51.png'),
            opacity:'0',
            left:'18.30%',
            top:'64.73%',
            pavilion:'5.2',
            width:'27px',
            height:'30px',
            index:9
        },
        {
            src:require('@/assets/other5n.png'),
            opacity:'0',
            left:'33.44%',
            top:'45.89%',
            pavilion:'5.2',
            width:'27px',
            height:'30px',
            index:'other'
        },
        {
            src:require('@/assets/other5l.png'),
            opacity:'0',
            left:'17.03%',
            top:'69.08%',
            pavilion:'5.2',
            width:'27px',
            height:'30px',
            index:'other2'
        },
        {
            src:require('@/assets/other5l.png'),
            opacity:'0',
            left:'22.08%',
            top:'71.04%',
            pavilion:'5.2',
            width:'27px',
            height:'30px',
            index:'other3'
        },
        /** 7.2号馆**/
        {
            src:require('@/assets/p71.png'),
            opacity:'0',
            left:'65.46%',
            top:'45.89%',
            pavilion:'7.2',
            width:'23px',
            height:'29px',
            index:0
        },
        {
            src:require('@/assets/p71.png'),
            opacity:'0',
            left:'64.04%',
            top:'52.42%',
            pavilion:'7.2',
            width:'23px',
            height:'29px',
            index:1
        },
        {
            src:require('@/assets/p71.png'),
            opacity:'0',
            left:'69.40%',
            top:'47.34%',
            pavilion:'7.2',
            width:'23px',
            height:'29px',
            index:2
        },
        {
            src:require('@/assets/p71.png'),
            opacity:'0',
            left:'67.98%',
            top:'54.11%',
            pavilion:'7.2',
            width:'23px',
            height:'29px',
            index:3
        },
        {
            src:require('@/assets/p71.png'),
            opacity:'0',
            left:'73.34%',
            top:'49.03%',
            pavilion:'7.2',
            width:'23px',
            height:'29px',
            index:4
        },
        {
            src:require('@/assets/p71.png'),
            opacity:'0',
            left:'72.08%',
            top:'55.56%',
            pavilion:'7.2',
            width:'23px',
            height:'29px',
            index:5
        },
        {
            src:require('@/assets/p71.png'),
            opacity:'0',
            left:'77.13%',
            top:'50.48%',
            pavilion:'7.2',
            width:'23px',
            height:'29px',
            index:6
        },
        {
            src:require('@/assets/p71.png'),
            opacity:'0',
            left:'76.02%',
            top:'57.24%',
            pavilion:'7.2',
            width:'23px',
            height:'29px',
            index:7
        },
        {
            src:require('@/assets/p71.png'),
            opacity:'0',
            left:'81.07%',
            top:'51.93%',
            pavilion:'7.2',
            width:'23px',
            height:'29px',
            index:8
        },
        {
            src:require('@/assets/p71.png'),
            opacity:'0',
            left:'79.97%',
            top:'58.70%',
            pavilion:'7.2',
            width:'23px',
            height:'29px',
            index:9
        },
        {
            src:require('@/assets/other7n.png'),
            opacity:'0',
            left:'61.83%',
            top:'44.44%',
            pavilion:'7.2',
            width:'23px',
            height:'29px',
            index:'other'
        },
        {
            src:require('@/assets/other7l.png'),
            opacity:'0',
            left:'83.60%',
            top:'60.14%',
            pavilion:'7.2',
            width:'23px',
            height:'29px',
            index:'other2'
        },
        {
            src:require('@/assets/other7l.png'),
            opacity:'0',
            left:'84.70%',
            top:'53.38%',
            pavilion:'7.2',
            width:'23px',
            height:'29px',
            index:'other3'
        },
        /** 8.2号馆**/
        {
            src:require('@/assets/p81.png'),
            opacity:'0',
            left:'68.45%',
            top:'31.16%',
            pavilion:'8.2',
            width:'23px',
            height:'29px',
            index:0
        },
        {
            src:require('@/assets/p81.png'),
            opacity:'0',
            left:'67.20%',
            top:'36.23%',
            pavilion:'8.2',
            width:'23px',
            height:'29px',
            index:1
        },
        {
            src:require('@/assets/p81.png'),
            opacity:'0',
            left:'72.40%',
            top:'32.85%',
            pavilion:'8.2',
            width:'23px',
            height:'29px',
            index:2
        },
        {
            src:require('@/assets/p81.png'),
            opacity:'0',
            left:'71.14%',
            top:'37.92%',
            pavilion:'8.2',
            width:'23px',
            height:'29px',
            index:3
        },
        {
            src:require('@/assets/p81.png'),
            opacity:'0',
            left:'76.34%',
            top:'34.3%',
            pavilion:'8.2',
            width:'23px',
            height:'29px',
            index:4
        },
        {
            src:require('@/assets/p81.png'),
            opacity:'0',
            left:'75.24%',
            top:'39.61%',
            pavilion:'8.2',
            width:'23px',
            height:'29px',
            index:5
        },
        {
            src:require('@/assets/p81.png'),
            opacity:'0',
            left:'80.13%',
            top:'36%',
            pavilion:'8.2',
            width:'23px',
            height:'29px',
            index:6
        },
        {
            src:require('@/assets/p81.png'),
            opacity:'0',
            left:'79.18%',
            top:'41.06%',
            pavilion:'8.2',
            width:'23px',
            height:'29px',
            index:7
        },
        {
            src:require('@/assets/p81.png'),
            opacity:'0',
            left:'84.07%',
            top:'37.44%',
            pavilion:'8.2',
            width:'23px',
            height:'29px',
            index:8
        },
        {
            src:require('@/assets/p81.png'),
            opacity:'0',
            left:'83.12%',
            top:'42.75%',
            pavilion:'8.2',
            width:'23px',
            height:'29px',
            index:9
        },
        {
            src:require('@/assets/other8n.png'),
            opacity:'0',
            left:'63.56%',
            top:'34.78%',
            pavilion:'8.2',
            width:'23px',
            height:'29px',
            index:'other'
        },
        {
            src:require('@/assets/other7l.png'),
            opacity:'0',
            left:'87.54%',
            top:'38.65%',
            pavilion:'8.2',
            width:'23px',
            height:'29px',
            index:'other2'
        },
        {
            src:require('@/assets/other7l.png'),
            opacity:'0',
            left:'86.59%',
            top:'43.96%',
            pavilion:'8.2',
            width:'23px',
            height:'29px',
            index:'other3'
        }
    ]
}


export  default exhititionList