const country=[
        {name:'Gabon',nameCH:'加蓬',value:1},
        {name:'Ethiopia',nameCH:'埃塞俄比亚',value:2},
        {name:'Zambia',nameCH:'赞比亚',value:3},
        {name:'Burkina Faso',nameCH:'布基纳法索',value:4},
        {name:'Tanzania',nameCH:'坦桑尼亚',value:5},
        {name:'Egypt',nameCH:'埃及',value:6},
        {name:'Uganda',nameCH:'乌干达',value:7},
        {name:'Tunisia',nameCH:'突尼斯',value:8},
        {name:'Togo',nameCH:'多哥',value:9},
        {name:'Swaziland',nameCH:'斯威士兰',value:10},  
        {name:'Sudan',nameCH:'苏丹',value:11},
        {name:'S. Sudan',nameCH:'南苏丹',value:12},
        {name:'Zimbabwe',nameCH:'津巴布韦',value:13},
        {name:'South Africa',nameCH:'南非',value:14},
        {name:'Somalia',nameCH:'索马里',value:15},
        {name:'Sierra Leone',nameCH:'塞拉利昂',value:16},
        {name:'Seychelles',nameCH:'塞舌尔',value:17},
        {name:'Senegal',nameCH:'塞内加尔',value:18},
        {name:'São Tomé and Principe',nameCH:'圣多美和普林西比',value:19},
        {name:'Saint Helena',nameCH:'圣赫勒拿',value:20},
        {name:'Rwanda',nameCH:'卢旺达',value:21},
        {name:'Guinea-Bissau',nameCH:'几内亚比绍',value:22},
        {name:'Nigeria',nameCH:'尼日利亚',value:23},
        {name:'Niger',nameCH:'尼日尔',value:24},
        {name:'Djibouti',nameCH:'吉布提',value:25},
        {name:'Eritrea',nameCH:'厄立特里亚',value:26},
        {name:'Eq. Guinea',nameCH:'赤道几内亚',value:27},
        {name:'Benin',nameCH:'贝宁',value:28},
        {name:'Dem. Rep. Congo',nameCH:'刚果（金）',value:29},
        {name:'Congo',nameCH:'刚果（布）',value:30},
        {name:'Comoros',nameCH:'科摩罗',value:31},
        {name:'China',nameCH:'中国',value:32},
        {name:'Chad',nameCH:'乍得',value:33},
        {name:'Central African Rep.',nameCH:'中非',value:34},
        {name:'Cape Verde',nameCH:'佛得角',value:35},
        {name:'Cameroon',nameCH:'喀麦隆',value:36},
        {name:'Burundi',nameCH:'布隆迪',value:37},
        {name:'Botswana',nameCH:'博茨瓦纳',value:38},
        {name:'Angola',nameCH:'安哥拉',value:39},
        {name:'Algeria',nameCH:'阿尔及利亚',value:40},
        {name:'Namibia',nameCH:'纳米比亚',value:41},
        {name:'Mozambique',nameCH:'莫桑比克',value:42},
        {name:'Mauritius',nameCH:'毛里求斯',value:43},
        {name:'Mauritania',nameCH:'毛里塔尼亚',value:44},
        {name:'Mali',nameCH:'马里',value:45},
        {name:'Malawi',nameCH:'马拉维',value:46},
        {name:'Madagascar',nameCH:'马达加斯加',value:47},
        {name:'Libya',nameCH:'利比亚',value:48},
        {name:'Liberia',nameCH:'利比里亚',value:49},
        {name:'Lesotho',nameCH:'莱索托',value:50},
        {name:'Kenya',nameCH:'肯尼亚',value:51},
        {name:"Côte d'Ivoire",nameCH:'科特迪瓦',value:52},
        {name:'Guinea',nameCH:'几内亚',value:53},
        {name:'Ghana',nameCH:'加纳',value:54},
        {name:'Gambia',nameCH:'冈比亚',value:55},
        {name:'Georgia',nameCH:'格鲁吉亚',value:56},
        {name:'Yemen',nameCH:'也门',value:57},
        {name:'Uzbekistan',nameCH:'乌兹别克斯坦',value:58},
        {name:'Turkmenistan',nameCH:'土库曼斯坦',value:59},
        {name:'Turkey',nameCH:'土耳其',value:60},
        {name:'United Arab Emirates',nameCH:'阿联酋',value:61},
        {name:'Thailand',nameCH:'泰国',value:62},
        {name:'Tajikistan',nameCH:'塔吉克斯坦',value:63},
        {name:'Syria',nameCH:'叙利亚',value:64},
        {name:'Vietnam',nameCH:'越南',value:65},
        {name:'Singapore',nameCH:'新加坡',value:66},
        {name:'Saudi Arabia',nameCH:'沙特阿拉伯',value:67},
        {name:'Qatar',nameCH:'卡塔尔',value:68},
        {name:'Timor-Leste',nameCH:'东帝汶',value:69},
        {name:'Philippines',nameCH:'菲律宾',value:70},
        {name:'Pakistan',nameCH:'巴基斯坦',value:71},
        {name:'Nepal',nameCH:'尼泊尔',value:72},
        {name:'Cyprus',nameCH:'塞浦路斯',value:73},
        {name:'Sri Lanka',nameCH:'斯里兰卡',value:74},
        {name:'Cambodia',nameCH:'柬埔寨',value:75},
        {name:'Myanmar',nameCH:'缅甸',value:76},
        {name:'Brunei',nameCH:'文莱',value:77},
        {name:'Bhutan',nameCH:'不丹',value:78},
        {name:'Armenia',nameCH:'亚美尼亚',value:79},
        {name:'Bangladesh',nameCH:'孟加拉',value:80},
        {name:'Bahrain',nameCH:'巴林',value:81},
        {name:'Azerbaijan',nameCH:'阿塞拜疆',value:82},
        {name:'Afghanistan',nameCH:'阿富汗',value:83},
        {name:'Oman',nameCH:'阿曼',value:84},
        {name:'Mongolia',nameCH:'蒙古',value:85},
        {name:'Malaysia',nameCH:'马来西亚',value:86},
        {name:'Lebanon',nameCH:'黎巴嫩',value:87},
        {name:'Lao PDR',nameCH:'老挝',value:88},
        {name:'Kyrgyzstan',nameCH:'吉尔吉斯斯坦',value:89},
        {name:'Kuwait',nameCH:'科威特',value:90},
        {name:'Korea',nameCH:'韩国',value:91},
        {name:'Dem. Rep. Korea',nameCH:'朝鲜',value:92},
        {name:'Jordan',nameCH:'约旦',value:93},
        {name:'Kazakhstan',nameCH:'哈萨克斯坦',value:94},
        {name:'Japan',nameCH:'日本',value:95},
        {name:'Israel',nameCH:'以色列',value:96},
        {name:'Iraq',nameCH:'伊拉克',value:97},
        {name:'Iran',nameCH:'伊朗',value:98},
        {name:'Indonesia',nameCH:'印度尼西亚',value:99},
        {name:'India',nameCH:'印度',value:100},
        {name:'Palestine',nameCH:'巴勒斯坦',value:101},
        {name:'Germany',nameCH:'德国',value:102},
        {name:'Bosnia and Herz.',nameCH:'波斯尼亚和黑塞哥维那',value:103},
        {name:'Isle of Man',nameCH:'马恩岛',value:104},
        {name:'Jersey',nameCH:'泽西岛',value:105},
        {name:'United Kingdom',nameCH:'英国',value:106},
        {name:'Macedonia',nameCH:'马其顿',value:107},
        {name:'Ukraine',nameCH:'乌克兰',value:108},
        {name:'Switzerland',nameCH:'瑞士',value:109},
        {name:'Sweden',nameCH:'瑞典',value:110},
        {name:'Spain',nameCH:'西班牙',value:111},
        {name:'Slovakia',nameCH:'斯洛伐克',value:112},
        {name:'Serbia',nameCH:'塞尔维亚共和国',value:113},
        {name:'Russia',nameCH:'俄罗斯联邦',value:114},
        {name:'Romania',nameCH:'罗马尼亚',value:115},
        {name:'Portugal',nameCH:'葡萄牙',value:116},
        {name:'Poland',nameCH:'波兰',value:117},
        {name:'Norway',nameCH:'挪威',value:118},
        {name:'Netherlands',nameCH:'荷兰',value:119},
        {name:'France',nameCH:'法国',value:120},
        {name:'Estonia',nameCH:'爱沙尼亚',value:121},
        {name:'Denmark',nameCH:'丹麦',value:122},
        {name:'Croatia',nameCH:'克罗地亚',value:123},
        {name:'Belarus',nameCH:'白俄罗斯',value:124},
        {name:'Bulgaria',nameCH:'保加利亚',value:125},
        {name:'Belgium',nameCH:'比利时',value:126},
        {name:'Austria',nameCH:'奥地利',value:127},
        {name:'Andorra',nameCH:'安道尔',value:128},
        {name:'Albania',nameCH:'阿尔巴尼亚',value:129},
        {name:'Morocco',nameCH:'摩洛哥',value:130},
        {name:'Montenegro',nameCH:'黑山共和国',value:131},
        {name:'Moldova',nameCH:'摩尔多瓦',value:132},
        {name:'Malta',nameCH:'马耳他',value:133},
        {name:'Luxembourg',nameCH:'卢森堡',value:134},
        {name:'Lithuania',nameCH:'立陶宛',value:135},
        {name:'Liechtenstein',nameCH:'列支敦士登',value:136},
        {name:'Latvia',nameCH:'拉脱维亚',value:137},
        {name:'Italy',nameCH:'意大利',value:138},
        {name:'Ireland',nameCH:'爱尔兰',value:139},
        {name:'Iceland',nameCH:'冰岛',value:140},
        {name:'Hungary',nameCH:'匈牙利',value:141},
        {name:'Greece',nameCH:'希腊',value:142},
        {name:'Greenland',nameCH:'格陵兰',value:143},
        {name:'United States',nameCH:'美国',value:144},
        {name:'Trinidad and Tobago',nameCH:'特立尼达和多巴哥',value:145},
        {name:'Saint Lucia',nameCH:'圣卢西亚',value:146},
        {name:'Puerto Rico',nameCH:'波多黎各',value:147},
        {name:'Panama',nameCH:'巴拿马',value:148},
        {name:'Nicaragua',nameCH:'尼加拉瓜',value:149},
        {name:'El Salvador',nameCH:'萨尔瓦多',value:150},
        {name:'Dominican Rep.',nameCH:'多米尼加',value:151},
        {name:'Dominica',nameCH:'多米尼克',value:152},
        {name:'Cuba',nameCH:'古巴',value:153},
        {name:'Costa Rica',nameCH:'哥斯达黎加',value:154},
        {name:'Canada',nameCH:'加拿大',value:155},
        {name:'Belize',nameCH:'伯利兹',value:156},
        {name:'Bermuda',nameCH:'百慕大',value:157},
        {name:'Barbados',nameCH:'巴巴多斯',value:158},
        {name:'Bahamas',nameCH:'巴哈马',value:159},
        {name:'Antigua and Barb.',nameCH:'安提瓜和巴布达',value:160},
        {name:'Montserrat',nameCH:'蒙特塞拉特',value:161},
        {name:'Mexico',nameCH:'墨西哥',value:162},
        {name:'Jamaica',nameCH:'牙买加',value:163},
        {name:'Honduras',nameCH:'洪都拉斯',value:164},
        {name:'Haiti',nameCH:'海地',value:165},
        {name:'Guatemala',nameCH:'危地马拉',value:166},
        {name:'Grenada',nameCH:'格林纳达',value:167},
        {name:'Kiribati',nameCH:'基里巴斯',value:168},
        {name:'Samoa',nameCH:'萨摩亚',value:169},
        {name:'Tonga',nameCH:'汤加',value:170},
        {name:'Papua New Guinea',nameCH:'巴布亚新几内亚',value:171},
        {name:'Palau',nameCH:'帕劳',value:172},
        {name:'Niue',nameCH:'纽埃',value:173},
        {name:'New Zealand',nameCH:'新西兰',value:174},
        {name:'Vanuatu',nameCH:'瓦努阿图',value:175},
        {name:'New Caledonia',nameCH:'新喀里多尼亚',value:176},
        {name:'Fiji',nameCH:'斐济',value:177},
        {name:'Australia',nameCH:'澳大利亚',value:178},
        {name:'American Samoa',nameCH:'美属萨摩亚',value:179},
        {name:'Guyana',nameCH:'圭亚那',value:180},
        {name:'Venezuela',nameCH:'委内瑞拉',value:181},
        {name:'Uruguay',nameCH:'乌拉圭',value:182},
        {name:'Suriname',nameCH:'苏里南',value:183},
        {name:'Peru',nameCH:'秘鲁',value:184},
        {name:'Paraguay',nameCH:'巴拉圭',value:185},
        {name:'Curaçao',nameCH:'库腊索岛',value:186},
        {name:'Ecuador',nameCH:'厄瓜多尔',value:187},
        {name:'Colombia',nameCH:'哥伦比亚',value:188},
        {name:'Chile',nameCH:'智利',value:189},
        {name:'Brazil',nameCH:'巴西',value:190},
        {name:'Bolivia',nameCH:'玻利维亚',value:191},
        {name:'Argentina',nameCH:'阿根廷',value:192},
        {name:'Guam',nameCH:'关岛',value:193},
        {name:'#N/A',nameCH:'台湾',value:194},
        {name:'#N/A',nameCH:'澳门',value:195},
        {name:'#N/A',nameCH:'香港',value:196},
        {name:'Czech Rep.',nameCH:'捷克',value:197},
        {name:'Finland',nameCH:'芬兰',value:198},
        {name:'Slovenia',nameCH:'斯洛文尼亚',value:199},
        {name:'Maldives',nameCH:'马尔代夫',value:200},
]
export default country;

export function compare(value){
    

    


}